---
name: BurgerCustomArmor
version: 1.0.0
main: Heisenburger69\BurgerCustomArmor\Main
api: 3.0.0
author: Heisenburger69
description: Create Custom Armor Sets with several abilities!
website: github.com/Heisenburger69
...
